PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS games (
  game_id INTEGER PRIMARY KEY,
  season INTEGER NOT NULL,
  game_date TEXT NOT NULL,
  game_type TEXT,
  status TEXT,
  scheduled_datetime TEXT,
  venue_id INTEGER,
  day_night TEXT,
  home_team_id INTEGER,
  away_team_id INTEGER,
  home_score INTEGER,
  away_score INTEGER,
  winning_team_id INTEGER,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS venue_dim (
  venue_id INTEGER PRIMARY KEY,
  venue_name TEXT NOT NULL,
  city TEXT,
  state TEXT,
  country TEXT DEFAULT 'USA',
  timezone TEXT NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  roof_type TEXT NOT NULL,
  weather_exposure_default INTEGER NOT NULL DEFAULT 1 CHECK(weather_exposure_default IN (0, 1)),
  statsapi_venue_name TEXT,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS game_weather_snapshots (
  game_id INTEGER NOT NULL,
  venue_id INTEGER NOT NULL,
  as_of_ts TEXT NOT NULL,
  target_game_ts TEXT NOT NULL,
  snapshot_type TEXT NOT NULL,
  source TEXT NOT NULL,
  source_priority INTEGER NOT NULL DEFAULT 1,
  hour_offset_from_first_pitch REAL,
  temperature_f REAL,
  humidity_pct REAL,
  pressure_hpa REAL,
  precipitation_mm REAL,
  precipitation_probability REAL,
  wind_speed_mph REAL,
  wind_gust_mph REAL,
  wind_direction_deg REAL,
  weather_code INTEGER,
  cloud_cover_pct REAL,
  is_day INTEGER CHECK(is_day IN (0, 1)),
  day_night_source TEXT,
  weather_exposure_flag INTEGER CHECK(weather_exposure_flag IN (0, 1)),
  statsapi_weather_condition_text TEXT,
  statsapi_wind_text TEXT,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, as_of_ts, snapshot_type, source),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE,
  FOREIGN KEY (venue_id) REFERENCES venue_dim(venue_id)
);

CREATE TABLE IF NOT EXISTS game_team_stats (
  game_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  side TEXT CHECK(side IN ('home', 'away')),
  runs INTEGER,
  hits INTEGER,
  errors INTEGER,
  batting_avg REAL,
  obp REAL,
  slg REAL,
  ops REAL,
  strikeouts INTEGER,
  walks INTEGER,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, team_id),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS game_pitcher_context (
  game_id INTEGER NOT NULL,
  side TEXT NOT NULL CHECK(side IN ('home', 'away')),
  pitcher_id INTEGER,
  pitcher_name TEXT,
  probable_pitcher_id INTEGER,
  probable_pitcher_name TEXT,
  probable_pitcher_known INTEGER NOT NULL DEFAULT 0 CHECK(probable_pitcher_known IN (0, 1)),
  season_era REAL,
  season_whip REAL,
  season_avg_allowed REAL,
  season_runs_per_9 REAL,
  season_strike_pct REAL,
  season_win_pct REAL,
  career_era REAL,
  stats_source TEXT,
  stats_as_of_date TEXT,
  season_stats_scope TEXT,
  season_stats_leakage_risk INTEGER NOT NULL DEFAULT 1 CHECK(season_stats_leakage_risk IN (0, 1)),
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, side),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS game_pitcher_appearances (
  game_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  side TEXT NOT NULL CHECK(side IN ('home', 'away')),
  pitcher_id INTEGER NOT NULL,
  pitcher_name TEXT,
  appearance_order INTEGER,
  is_starter INTEGER NOT NULL DEFAULT 0 CHECK(is_starter IN (0, 1)),
  is_reliever INTEGER NOT NULL DEFAULT 1 CHECK(is_reliever IN (0, 1)),
  outs_recorded INTEGER,
  innings_pitched REAL,
  batters_faced INTEGER,
  pitches INTEGER,
  strikes INTEGER,
  hits INTEGER,
  walks INTEGER,
  strikeouts INTEGER,
  runs INTEGER,
  earned_runs INTEGER,
  home_runs INTEGER,
  holds INTEGER,
  save_flag INTEGER,
  blown_save_flag INTEGER,
  inherited_runners INTEGER,
  inherited_runners_scored INTEGER,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, pitcher_id),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS team_bullpen_game_state (
  game_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  side TEXT NOT NULL CHECK(side IN ('home', 'away')),
  as_of_ts TEXT NOT NULL,
  stats_scope TEXT NOT NULL DEFAULT 'prior_completed_games_only',
  freshness_method TEXT NOT NULL,
  season_games_in_sample INTEGER NOT NULL DEFAULT 0,
  bullpen_pitchers_in_sample INTEGER NOT NULL DEFAULT 0,
  bullpen_appearances_season INTEGER NOT NULL DEFAULT 0,
  bullpen_outs_season INTEGER NOT NULL DEFAULT 0,
  bullpen_era_season REAL,
  bullpen_whip_season REAL,
  bullpen_runs_per_9_season REAL,
  bullpen_k_rate_season REAL,
  bullpen_bb_rate_season REAL,
  bullpen_k_minus_bb_rate_season REAL,
  bullpen_hr_rate_season REAL,
  bullpen_outs_last1d INTEGER NOT NULL DEFAULT 0,
  bullpen_outs_last3d INTEGER NOT NULL DEFAULT 0,
  bullpen_outs_last5d INTEGER NOT NULL DEFAULT 0,
  bullpen_outs_last7d INTEGER NOT NULL DEFAULT 0,
  bullpen_pitches_last1d INTEGER NOT NULL DEFAULT 0,
  bullpen_pitches_last3d INTEGER NOT NULL DEFAULT 0,
  bullpen_pitches_last5d INTEGER NOT NULL DEFAULT 0,
  bullpen_appearances_last3d INTEGER NOT NULL DEFAULT 0,
  bullpen_appearances_last5d INTEGER NOT NULL DEFAULT 0,
  relievers_used_yesterday_count INTEGER NOT NULL DEFAULT 0,
  relievers_used_last3d_count INTEGER NOT NULL DEFAULT 0,
  relievers_back_to_back_count INTEGER NOT NULL DEFAULT 0,
  relievers_2_of_last3_count INTEGER NOT NULL DEFAULT 0,
  high_usage_relievers_last3d_count INTEGER NOT NULL DEFAULT 0,
  freshness_score REAL,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, side, as_of_ts),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS team_bullpen_top_relievers (
  game_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  side TEXT NOT NULL CHECK(side IN ('home', 'away')),
  as_of_ts TEXT NOT NULL,
  stats_scope TEXT NOT NULL DEFAULT 'prior_completed_games_only',
  ranking_method TEXT NOT NULL,
  top_n INTEGER NOT NULL,
  n_available INTEGER NOT NULL DEFAULT 0,
  selected_pitcher_ids_json TEXT NOT NULL DEFAULT '[]',
  topn_appearances_season INTEGER NOT NULL DEFAULT 0,
  topn_outs_season INTEGER NOT NULL DEFAULT 0,
  topn_era_season REAL,
  topn_whip_season REAL,
  topn_runs_per_9_season REAL,
  topn_k_rate_season REAL,
  topn_bb_rate_season REAL,
  topn_k_minus_bb_rate_season REAL,
  topn_outs_last3d INTEGER NOT NULL DEFAULT 0,
  topn_pitches_last3d INTEGER NOT NULL DEFAULT 0,
  topn_appearances_last3d INTEGER NOT NULL DEFAULT 0,
  topn_back_to_back_count INTEGER NOT NULL DEFAULT 0,
  topn_freshness_score REAL,
  quality_dropoff_vs_team REAL,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, side, as_of_ts, top_n),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS player_handedness_dim (
  player_id INTEGER PRIMARY KEY,
  player_name TEXT,
  bat_side TEXT CHECK(bat_side IN ('L', 'R', 'S')),
  pitch_hand TEXT CHECK(pitch_hand IN ('L', 'R', 'S')),
  primary_position_code TEXT,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS game_lineup_snapshots (
  game_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  side TEXT NOT NULL CHECK(side IN ('home', 'away')),
  as_of_ts TEXT NOT NULL,
  snapshot_type TEXT NOT NULL,
  lineup_status TEXT NOT NULL,
  player_id INTEGER NOT NULL,
  player_name TEXT,
  batting_order INTEGER,
  position_code TEXT,
  bat_side TEXT CHECK(bat_side IN ('L', 'R', 'S')),
  pitch_hand TEXT CHECK(pitch_hand IN ('L', 'R', 'S')),
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, side, as_of_ts, batting_order),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS team_lineup_game_state (
  game_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  side TEXT NOT NULL CHECK(side IN ('home', 'away')),
  as_of_ts TEXT NOT NULL,
  snapshot_type TEXT NOT NULL,
  lineup_status TEXT NOT NULL,
  lineup_known_flag INTEGER NOT NULL DEFAULT 0 CHECK(lineup_known_flag IN (0, 1)),
  announced_lineup_count INTEGER NOT NULL DEFAULT 0,
  lineup_l_count INTEGER,
  lineup_r_count INTEGER,
  lineup_s_count INTEGER,
  top3_l_count INTEGER,
  top3_r_count INTEGER,
  top3_s_count INTEGER,
  top5_l_count INTEGER,
  top5_r_count INTEGER,
  top5_s_count INTEGER,
  lineup_lefty_pa_share_proxy REAL,
  lineup_righty_pa_share_proxy REAL,
  lineup_switch_pa_share_proxy REAL,
  lineup_balance_score REAL,
  lineup_quality_metric TEXT,
  lineup_quality_mean REAL,
  top3_lineup_quality_mean REAL,
  top5_lineup_quality_mean REAL,
  lineup_vs_rhp_quality REAL,
  lineup_vs_lhp_quality REAL,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, side, as_of_ts),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS team_platoon_splits (
  game_id INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  side TEXT NOT NULL CHECK(side IN ('home', 'away')),
  as_of_ts TEXT NOT NULL,
  vs_pitch_hand TEXT NOT NULL CHECK(vs_pitch_hand IN ('L', 'R')),
  stats_scope TEXT NOT NULL DEFAULT 'prior_completed_games_only',
  games_in_sample INTEGER NOT NULL DEFAULT 0,
  plate_appearances INTEGER NOT NULL DEFAULT 0,
  batting_avg REAL,
  obp REAL,
  slg REAL,
  ops REAL,
  runs_per_game REAL,
  strikeout_rate REAL,
  walk_rate REAL,
  source_updated_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, side, as_of_ts, vs_pitch_hand),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feature_rows (
  game_id INTEGER NOT NULL,
  feature_version TEXT NOT NULL,
  as_of_ts TEXT NOT NULL,
  feature_payload_json TEXT NOT NULL,
  source_contract_status TEXT NOT NULL DEFAULT 'valid',
  source_contract_issues_json TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, feature_version, as_of_ts),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS labels (
  game_id INTEGER PRIMARY KEY,
  did_home_win INTEGER CHECK (did_home_win IN (0, 1)),
  home_score INTEGER,
  away_score INTEGER,
  run_differential INTEGER,
  total_runs INTEGER,
  label_source TEXT DEFAULT 'statsapi',
  settled_at TEXT,
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ingestion_runs (
  run_id TEXT PRIMARY KEY,
  mode TEXT NOT NULL CHECK(mode IN ('init-db', 'backfill', 'incremental', 'dq')),
  status TEXT NOT NULL CHECK(status IN ('running', 'success', 'failed', 'blocked', 'stubbed')),
  partition_key TEXT,
  started_at TEXT NOT NULL,
  ended_at TEXT,
  config_json TEXT,
  request_count INTEGER NOT NULL DEFAULT 0,
  note TEXT
);

CREATE TABLE IF NOT EXISTS ingestion_checkpoints (
  job_name TEXT NOT NULL,
  partition_key TEXT NOT NULL,
  cursor_json TEXT,
  last_game_id INTEGER,
  attempts INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'running',
  updated_at TEXT NOT NULL,
  last_error TEXT,
  PRIMARY KEY (job_name, partition_key)
);

CREATE TABLE IF NOT EXISTS dq_results (
  run_id TEXT NOT NULL,
  check_name TEXT NOT NULL,
  severity TEXT NOT NULL CHECK(severity IN ('info', 'warn', 'error')),
  passed INTEGER NOT NULL CHECK(passed IN (0, 1)),
  expected_value REAL,
  observed_value REAL,
  details_json TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (run_id, check_name),
  FOREIGN KEY (run_id) REFERENCES ingestion_runs(run_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS odds_snapshot (
  game_id INTEGER NOT NULL,
  snapshot_ts TEXT NOT NULL,
  bookmaker TEXT NOT NULL,
  market_type TEXT NOT NULL DEFAULT 'moneyline',
  home_price INTEGER,
  away_price INTEGER,
  implied_home_prob REAL,
  implied_away_prob REAL,
  source TEXT,
  note TEXT NOT NULL DEFAULT 'forward_only',
  ingested_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (game_id, snapshot_ts, bookmaker, market_type),
  FOREIGN KEY (game_id) REFERENCES games(game_id) ON DELETE CASCADE
);
